image:
  file: .gitpod.dockerfile

# Commands to start on workspace startup
tasks:
  - name: Install / Migrate
    init: >
      docker compose build
  - name: Start Application
    command: >
      docker compose up -d
# Ports to expose on workspace startup
ports:
  - port: 8001
    onOpen: open-preview
  - port: 8002
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false

vscode:
  extensions:
    - "denoland.vscode-deno"
    - "trunk.io"
