version: "3.9"
services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.29
    ports:
      - "8002:3306"
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: {}
